server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

identityServiceUrl: ${IDENTITY_SERVICE_URL}

rateLimitConfig:
  enabled: true
  rateLimitStrategy: ${RATE_LIMIT_STRATEGY_NAME}

jedisPoolConfiguration:
  maxTotal: 128
  endpoint: ${JEDIS_ENDPOINT}
  port: ${PORT}

rateLimitTokenBucketConfig:
  bucketCapacity: 1
  tokenPerSecond: 1
  luaScriptPath: lua/TokenBucket.lua
