server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

identityServiceUrl: "http://localhost:8080"

rateLimitConfig:
  enabled: true
  rateLimitStrategy: 'TOKEN_BUCKET'

jedisPoolConfiguration:
  maxTotal: 128
  endpoint: 'localhost'
  port: 6379

rateLimitTokenBucketConfig:
  bucketCapacity: 1
  tokenPerSecond: 1
  luaScriptPath: lua/TokenBucket.lua
