server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083
  # Limit the thread pool so Jetty doesn't consume all RAM during a traffic spike
  maxThreads: 96
  minThreads: 8

logging:
  level: INFO
  loggers:
    org.nath.sns: DEBUG
    org.nath.sns.resource: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601}] [%X{requestId}] %c: %m%n"

identityServiceUrl: "http://localhost:8080"

rateLimitConfig:
  enabled: true
  rateLimitStrategy: 'TOKEN_BUCKET'

jedisPoolConfiguration:
  maxTotal: 128
  endpoint: 'localhost'
  port: 6379

rateLimitTokenBucketConfig:
  bucketCapacity: 1
  tokenPerSecond: 1
  luaScriptPath: lua/TokenBucket.lua
