server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  # Limit the thread pool so Jetty doesn't consume all RAM during a traffic spike
  maxThreads: 96
  minThreads: 8

logging:
  level: INFO
  loggers:
    org.nath.sns.service: DEBUG
    org.nath.sns.resource: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601}] [%X{requestId}] %c: %m%n"

jwt:
  privateKeyPath: 'D:\Uday\Documents\Projects\Social\keys\private_key.pem'
  publicKeyPath: 'D:\Uday\Documents\Projects\Social\keys\public_key.pem'
  expirationMs: 3600000 # 1 hour

database:
  # The JDBC driver class for PostgreSQL
  driverClass: org.postgresql.Driver

  # Your local PostgreSQL credentials
  user: social_app
  password: 123456789

  # The JDBC URL to your local database
  url: jdbc:postgresql://localhost:5432/social

  # Connection pool and Hibernate specific properties
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: none

  # Do not open more than 3 connections on the free tier
  initialSize: 10
  minSize: 10
  maxSize: 100

  # Close connections if idle for 10 minutes to free up DB resources
  maxConnectionAge: 10m

flyway:
  # Optional: Tell flyway where to look. By default it looks in db/migration
  locations: [classpath:db/migration]
  baselineOnMigrate: true
  baseLineVersion: "0"
  placeholders:
      admin_password_hash: $2a$12$hlD0jaA9lHz2yKsFScOq4.8i3m1MfZy8GU5lxRhuAkF4Jj2XWJnqi