server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.nath.sns.service: DEBUG
    org.nath.sns.resource: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601}] [%X{requestId}] %c: %m%n"

jwt:
  privateKeyPath: /run/secrets/identity_private_key
  publicKeyPath: /run/secrets/identity_public_key
  expirationMs: 3600000 # 1 hour

database:
  # The JDBC driver class for PostgreSQL
  driverClass: org.postgresql.Driver

  # Your local PostgreSQL credentials
  user: ${POSTGRESQL_DB_USER}
  password: ${POSTGRESQL_DB_PASSWORD}

  # The JDBC URL to your local database
  url: jdbc:postgresql://${POSTGRESQL_DB_URL}:${POSTGRESQL_DB_PORT}/${POSTGRESQL_DB_NAME}

  # Connection pool and Hibernate specific properties
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update # Automatically creates/updates tables based on your @Entity classes