server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.nath.sns.service: DEBUG
    org.nath.sns.resource: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601}] [%X{requestId}] %c: %m%n"

jwt:
  privateKeyPath: 'D:\Uday\Documents\Projects\Social\keys\private_key.pem'
  publicKeyPath: 'D:\Uday\Documents\Projects\Social\keys\public_key.pem'
  expirationMs: 3600000 # 1 hour

database:
  # The JDBC driver class for PostgreSQL
  driverClass: org.postgresql.Driver

  # Your local PostgreSQL credentials
  user: social_app
  password: 123456789

  # The JDBC URL to your local database
  url: jdbc:postgresql://localhost:5432/social

  # Connection pool and Hibernate specific properties
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update # Automatically creates/updates tables based on your @Entity classes